language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - 8
  - 7
  - 6
  - 4

stages:
  - test
  - name: publish
    if: branch = master

env:
  - BUILD_LEADER_ID=6

jobs:
  include:
    - stage: test
      script: yarn test
    - stage: publish
      node_js: 8
      script: echo Publish
      after_success:
        - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

install: yarn --ignore-engines
