language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - 9
  - 8
  - 6
  - 10

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

install: yarn --ignore-engines
after_success:
  - npm run semantic-release
