language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

stages:
  - test
  - name: publish
    if: branch = master

jobs:
  include:
    - stage: test
      script: yarn test
      node_js:
        - 8
        - 7
        - 6
        - 4
    - stage: publish
      script: echo Publish
      node_js: 8
      after_success:
        - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
