language: node_js

notifications:
  email: false

before_install:
  - npm i -g npm@latest

node_js:
  - 8
  - 7
  - 6
  - 4

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

install:
  - npm i
  - npm ls
