language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

before_install:
  - npm i -g npm@latest

node_js:
  - 8
  - 7
  - 6
  - 4

after_success:
  - npx -p node@8 npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

install:
  - npm i
